name: Update Profile Activity

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [profile-update]

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update README with latest activity"
          MAX_LINES: 10
          GH_USERNAME: Olabits-Dev
